---
- name: Include Debian specific tasks
  include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include RedHat specific tasks
  include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Suse specific tasks
  include: Suse.yml
  when: ansible_os_family == 'Suse'

- name: Check for unsupported target operating system
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: xinetd_supported_os is not defined

- name: ensure xinetd is started
  service:
    name: xinetd
    state: started
    enabled: yes
